# Generated by Django 3.2 on 2021-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_notified',
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
