# Generated by Django 3.1.7 on 2021-04-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='max_count',
            new_name='max_app_count',
        ),
    ]
