# Generated by Django 3.1.7 on 2021-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.SlugField()),
                ('ratings', models.FloatField(blank=True, default=None, null=True)),
                ('dev_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_update_info', models.DateTimeField(auto_now=True, null=True)),
                ('count_reviews', models.IntegerField()),
            ],
        ),
    ]
