# Generated by Django 3.1.7 on 2021-04-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210411_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='integration',
            old_name='integration_type_id',
            new_name='integration_type',
        ),
        migrations.RenameField(
            model_name='integration',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_type_id',
            new_name='subscription_type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
