# Generated by Django 3.1.7 on 2021-04-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210411_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='app',
            field=models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.ForeignKey(db_column='integration_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.integrationtype'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='app',
            field=models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(db_column='subscription_type_id', on_delete=django.db.models.deletion.CASCADE, to='api.subscriptiontype'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
